### ISSUE TITLE
Website Link Broken

### ISSUE THREAD

**Issue by joelhandwell** [mojohaus/gwt-maven-plugin#1]
Not sure if this issue tracker is proper place to report, but http://mojo.codehaus.org/gwt-maven-plugin/ is not working.

**Comment by craigsumner** [comment]
I eventually found what I was looking for here:

https://gwt-maven-plugin.github.io/gwt-maven-plugin/

and here:

https://github.com/gwt-maven-plugin/gwt-maven-plugin
