### ISSUE TITLE
documentation link is incorrect

### ISSUE THREAD

**Issue by magick93** [mojohaus/gwt-maven-plugin#3]
The link to http://mojo.codehaus.org/gwt-maven-plugin/ just redirects to http://www.mojohaus.org/

Should be a link to the actual documentation.

**Comment by craigsumner** [comment]
I eventually found what I was looking for here:

https://gwt-maven-plugin.github.io/gwt-maven-plugin/

and here:

https://github.com/gwt-maven-plugin/gwt-maven-plugin
