### ISSUE TITLE
jsinterop

### ISSUE THREAD

**Issue by lilletech** [mojohaus/gwt-maven-plugin#4]
hi,
since today using gwt-2.8.0 snapshot or beta1 with gwt-maven-plugin 2.8.0 snapshot i've have an error

[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.8.0-SNAPSHOT:compile (default) on project cloud-web-mobile-patient: Failed to resolve artifact: Some problems were encountered while processing the POMs:
[ERROR] [ERROR] 'dependencies.dependency.version' for com.google.jsinterop:jsinterop-annotations:jar is missing. @ line 16, column 21
[ERROR] [ERROR] 'dependencies.dependency.version' for com.google.jsinterop:jsinterop-annotations:jar:sources is missing. @ line 20, column 21
[ERROR] for project

**Comment by branflake2267** [comment]
I'm guessing but I think you may have to add the gwt sdk dependency to the plugin.
